# -*- coding: utf-8 -*-
"""AeroLoyalty-Membership-Churn-Retention-Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBqTAqbg4kCJGJpgw7K_vZfl8pWJeTE7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from google.colab import drive

"""# Load Data"""

from google.colab import drive
drive.mount('/content/drive')

flight_df = pd.read_csv('/content/drive/MyDrive/Customer Flight Activity.csv')
loyalty_df = pd.read_csv('/content/drive/MyDrive/Customer Loyalty History.csv')

"""# Data Preprocessing

### **flight_df** (flight data by month)
"""

#Check for missing values
flight_df.isnull().sum()

#Check for duplicates
flight_df.duplicated().sum()

#Drop duplicates
flight_df=flight_df.drop_duplicates()

#Checkfor duplicate entries for the same 'Loyalty Number', 'Year', and 'Month':
duplicate_id_date = flight_df[flight_df.duplicated(subset=['Loyalty Number', 'Year', 'Month'], keep=False)]

if not duplicate_id_date.empty:
    print(f"Found {len(duplicate_id_date)} duplicate entries for the same Loyalty Number and date.")
    display(duplicate_id_date.sort_values(by=['Loyalty Number', 'Year', 'Month']))
else:
    print("No duplicate entries found for the same Loyalty Number and date.")

#Order the duplicate entries by largest Total Flights
flight_df = flight_df.sort_values(['Loyalty Number', 'Year', 'Month', 'Total Flights'],
                    ascending=[True, True, True, False])
flight_df

# Keep the entry with the largest Total Flights
flight_df = flight_df.drop_duplicates(subset=['Loyalty Number', 'Year', 'Month'], keep='first')
flight_df = flight_df.reset_index(drop=True)
flight_df

#Covnvert the Year and Month datatype
flight_df['year_month'] = flight_df['Year'].astype(str) + flight_df['Month'].astype(str).str.zfill(2)

"""### **loyalty_df** (Member profiles)"""

#Check for missing values
display(loyalty_df.isnull().sum())

#Check for duplicates
loyalty_df.duplicated().sum()

#Check for negative values
numeric_df = loyalty_df.select_dtypes(include=np.number)
neg_cols = numeric_df.columns[(numeric_df < 0).any()].tolist()

print(f"Columns with negative values: {neg_cols}")

#Drop unused columns and convert Salary
loyalty_df=loyalty_df.drop(['Postal Code','Country','Province','City',], axis=1)
loyalty_df['Salary'] = loyalty_df['Salary'].abs() # Make negative salary values positive
loyalty_df.reset_index(drop=True, inplace=True)
loyalty_df

"""### **flight_summary** (Total Flights and Total Points)"""

aggregation_columns = ['Total Flights',
    'Flights Booked',
    'Flights with Companions',
    'Distance',
    'Points Accumulated',
    'Points Redeemed',
    'Dollar Cost Points Redeemed'
]

#Dictionary to sum all columns
agg_dict = {col: 'sum' for col in aggregation_columns}

flights_summary = (
    flight_df
    .groupby('Loyalty Number')
    .agg(agg_dict)
    .reset_index()
)

flights_summary.columns = ['Loyalty Number'] + [f'Total_{col.replace(" ", "_")}' for col in aggregation_columns]
flights_summary['Avg_Distance_Per_Flight'] = (
    flights_summary['Total_Distance'] / flights_summary['Total_Total_Flights'].replace(0, np.nan)
).fillna(0)

flights_summary.head()

"""### **final** Final DF (contains every member's background, total flights, total points, redeem rate and average flight distance)"""

final = pd.merge(loyalty_df, flights_summary, on='Loyalty Number', how='inner')
final['Churn'] = np.where(final['Cancellation Month'].isna(), 0, 1) #Add Churn column
final['Point Usage Percentage'] = (final['Total_Points_Redeemed'] / final['Total_Points_Accumulated'])*100
final['Point Usage Percentage'] = final['Point Usage Percentage'].fillna(0)
final

#Members with 0 flights booked
final[final['Total_Flights_Booked']==0]

# Start date column in YYYYMM
final['start_yyyymm'] = (
    final['Enrollment Year'].astype(int).astype(str) +
    final['Enrollment Month'].astype(int).astype(str).str.zfill(2)
)

# End date column in YYYYMM, fill current members with 201812
final['end_yyyymm'] = (
    final['Cancellation Year'].fillna(0).astype(int).astype(str).str.zfill(4) +
    final['Cancellation Month'].fillna(0).astype(int).astype(str).str.zfill(2)
)

final.loc[final['end_yyyymm'] == '000000', 'end_yyyymm'] = np.nan

final.head()

#Calculate member lifecycle in months
def calculate_lifecycle_months(row):
    """Calculate member lifecycle in months"""
    start_year = int(row['start_yyyymm'][:4])
    start_month = int(row['start_yyyymm'][4:])

    # If not yet cancelled, use 2018/12 as end date
    if pd.isna(row['end_yyyymm']):
        end_year = 2018
        end_month = 12
    else:
        end_year = int(row['end_yyyymm'][:4])
        end_month = int(row['end_yyyymm'][4:])

    months = (end_year - start_year) * 12 + (end_month - start_month)
    return months

final['lifecycle_months'] = final.apply(calculate_lifecycle_months, axis=1)

#Filter members with lifecycle <= 12 months
short_lifecycle = final[final['lifecycle_months'] <= 12].copy()

print(f"Total members: {len(final)}")
print(f"Members with lifecycle <= 1 year: {len(short_lifecycle)}")
print(f"Percentage: {len(short_lifecycle)/len(final)*100:.2f}%\n")

#Create point usage percentage groups
def categorize_exchange_rate(rate):
    """Categorize exchange rate into groups"""
    if pd.isna(rate):
        return 'Missing'
    elif rate <= 5:
        return '0-5'
    elif rate <= 10:
        return '5-10'
    elif rate <= 15:
        return '10-15'
    elif rate <= 20:
        return '15-20'
    elif rate <= 25:
        return '20-25'
    elif rate <= 30:
        return '25-30'
    elif rate <= 35:
        return '30-35'
    elif rate <= 40:
        return '35-40'
    elif rate <= 45:
        return '40-45'
    elif rate <= 50:
        return '45-50'
    elif rate <= 55:
        return '55-60'
    elif rate <= 60:
        return '60-65'
    elif rate <= 65:
        return '65-70'
    elif rate <= 70:
        return '70-75'
    elif rate <= 75:
        return '75-80'
    elif rate <= 80:
        return '80-85'
    elif rate <= 85:
        return '85-90'
    elif rate <= 90:
        return '90-95'
    elif rate <= 95:
        return '95-100'
    else:
        return '>100'

# Categorize Point Usage Percentage column
final['exchange_rate_group'] = final['Point Usage Percentage'].apply(categorize_exchange_rate)

"""### **current_members**"""

current_members=final[final['Cancellation Year'].isna()]

"""### **cancelled_people** (all members that churned)"""

cancelled_people = final[final['Cancellation Year'].notna()]
cancelled_people

"""### **cancelled_20172018** (members cancelled in 2017 or 2018)"""

df = flight_df.merge(
    cancelled_people[['Loyalty Number', 'Cancellation Year', 'Cancellation Month']],
    on='Loyalty Number',
    how='left'
)

# Filter for cancelled customers in 2017 or 2018
cancelled_20172018 = df[(df['Cancellation Year']==2017) | (df['Cancellation Year']==2018)].copy()

cancelled_20172018['YearMonth'] = cancelled_20172018['Year'].astype(str).str.zfill(2) + cancelled_20172018['Month'].astype(str).str.zfill(2)
cancelled_20172018['YearMonth'] = cancelled_20172018['YearMonth'].astype(int)

# Fill NaN with 0 and convert
cancelled_20172018['CancellationYearMonth'] = cancelled_20172018['Cancellation Year'].fillna(0).astype(int).astype(str).str.zfill(2) + cancelled_20172018['Cancellation Month'].fillna(0).astype(int).astype(str).str.zfill(2)
cancelled_20172018['CancellationYearMonth'] = cancelled_20172018['CancellationYearMonth'].astype(int)
cancelled_20172018

"""#EDA"""

#Explore enrollment and cancellation distribution
fig, axes = plt.subplots(1, 2, figsize=(6, 3))

# Enrollment year distribution
cancelled_people["Enrollment Year"].value_counts().sort_index().plot(kind="bar", ax=axes[0], color='rosybrown')
axes[0].set_title("Enrollment Year Distribution")
axes[0].set_xlabel("Year")
axes[0].set_ylabel("Number of Members")

# Cancellation year distribution
cancelled_people["Cancellation Year"].value_counts().sort_index().plot(kind="bar", ax=axes[1], color='rosybrown')
axes[1].set_title("Cancellation Year Distribution")
axes[1].set_xlabel("Year")
axes[1].set_ylabel("Number of Cancellations")

plt.tight_layout()
plt.show()

#Churn rate and Active Member Count

total_churn = []
active_members_over_time = []
previous_churned = 0  # cumulative churned members

years = sorted(set(final['Enrollment Year']).union(final['Cancellation Year'].dropna().astype(int)))
for year in years:
    # Total members enrolled up to this year
    enrolled_up_to_year = len(final[final['Enrollment Year'] <= year])

    # Subtract previously churned members
    active_members_start_year = enrolled_up_to_year - previous_churned

    # Members who churned this year
    churned_this_year = len(final[final['Cancellation Year'] == year])

    # Update cumulative churned
    previous_churned += churned_this_year

    # Calculate churn rate
    churn_rate = (churned_this_year / active_members_start_year * 100) if active_members_start_year > 0 else 0

    total_churn.append({'Year': year, 'Total Churn Rate (%)': churn_rate})
    active_members_over_time.append({'Year': year, 'Active Members': active_members_start_year})

# Convert to DataFrame
total_churn_df = pd.DataFrame(total_churn)
active_members_df = pd.DataFrame(active_members_over_time)

print("Annual Churn Rate:")
print(total_churn_df)
print("\nActive Member Count Over Time:")
print(active_members_df)

# Plot Annual Churn Rate
plt.figure(figsize=(6,3))
plt.plot(total_churn_df['Year'], total_churn_df['Total Churn Rate (%)'], marker='o', linestyle='-', color='rosybrown')
plt.title('Annual Churn Rate')
plt.xlabel('Year')
plt.ylabel('Churn Rate (%)')
plt.xticks(total_churn_df['Year'])
plt.show()

# Plot Active Member Count Over Time
plt.figure(figsize=(6,3))
plt.bar(active_members_df['Year'], active_members_df['Active Members'], color='rosybrown')
plt.title('Active Member Count Per Year')
plt.xlabel('Year')
plt.ylabel('Number of Active Members')
plt.xticks(active_members_df['Year'])  # show every year
plt.show()

#Churn Rate by Loyalty Card
years = sorted(set(final['Enrollment Year']).union(final['Cancellation Year'].dropna().astype(int)))
churn_records = []

for year in years:
    for card, group in final.groupby('Loyalty Card'):
        started = len(group[group['Enrollment Year'] <= year])
        churned = len(group[group['Cancellation Year'] == year])
        churn_rate = (churned / started * 100) if started > 0 else 0
        churn_records.append({'Year': year, 'Loyalty Card': card, 'Churn Rate (%)': churn_rate})

churn_df = pd.DataFrame(churn_records)
churn_df

#Flight activity correlation map
numerical_columns = flight_df.select_dtypes(include=np.number)
flight_correlation_matrix = numerical_columns.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(flight_correlation_matrix, annot=True, fmt=".2f", cmap='rocket', annot_kws={'fontsize':12}) # Increased font size
plt.title('Correlation Matrix of Flight Activity Features')
plt.show()

#Calculate percentage of members with lifecycle<=1 year in each group
group_analysis = final.groupby('exchange_rate_group').agg({
    'lifecycle_months': [
        ('total_count', 'count'),
        ('short_lifecycle_count', lambda x: (x <= 12).sum())
    ]
}).reset_index()

group_analysis.columns = ['exchange_rate_group', 'total_count', 'short_lifecycle_count']
group_analysis['short_lifecycle_ratio'] = (
    group_analysis['short_lifecycle_count'] / group_analysis['total_count'] * 100
)
group_analysis['long_lifecycle_pct'] = 100 - group_analysis['short_lifecycle_ratio']

# Sort groups
group_order = ['0-5', '5-10', '10-15', '15-20', '20-25', '25-30',
               '30-35', '35-40', '40-45', '45-50', '50-55', '55-60',
               '60-65', '65-70', '70-75', '75-80', '80-85', '85-90',
               '90-95', '95-100', '>100', 'Missing']
group_analysis['sort_key'] = group_analysis['exchange_rate_group'].apply(
    lambda x: group_order.index(x) if x in group_order else 999
)
group_analysis = group_analysis.sort_values('sort_key').drop('sort_key', axis=1)

print("Percentage of members with lifecycle<=1 year by exchange rate group:")
print(group_analysis)

#Visualize percentage of members with lifecycle<=1 year by group
fig1, ax1 = plt.subplots(figsize=(8, 5))

bars_short = ax1.bar(
    range(len(group_analysis)),
    group_analysis['short_lifecycle_ratio'],
    label='Lifecycle <= 1 Year',
    color='rosybrown'
)

bars_long = ax1.bar(
    range(len(group_analysis)),
    group_analysis['long_lifecycle_pct'],
    bottom=group_analysis['short_lifecycle_ratio'],
    label='Lifecycle > 1 Year',
    color = 'white'
)
ax1.set_xlabel('Redeem Rate(%)')
ax1.set_ylabel('Members with Lifecycle ≤ 1 Year (%)')
ax1.set_title('Percentage of Short-Lifecycle Members by Redeem Rate')
ax1.set_xticks(range(len(group_analysis)))
ax1.set_xticklabels(group_analysis['exchange_rate_group'], rotation=45, ha='right')
ax1.axhline(y=50, color='red', linestyle='--', linewidth=1, alpha=0.5, label='50% Reference Line')

for i, ratio in enumerate(group_analysis['short_lifecycle_ratio']):
    ax1.text(i, ratio + 1, f'{ratio:.1f}%',
             ha='center', va='bottom', fontsize=9)

ax1.legend()
plt.tight_layout()
plt.show()

#Visualize number if members in Redeem Rate Groups
fig2, ax2 = plt.subplots(figsize=(8, 5))
bars2 = ax2.bar(range(len(group_analysis)),
                group_analysis['total_count'], color='rosybrown'
                )
ax2.set_xlabel('Redeem Rate(%)')
ax2.set_ylabel('Total Member Count')
ax2.set_title('Distribution of Total Members by Redeem Rate')
ax2.set_xticks(range(len(group_analysis)))
ax2.set_xticklabels(group_analysis['exchange_rate_group'], rotation=45, ha='right')

for i, count in enumerate(group_analysis['total_count']):
    ax2.text(i, count + max(group_analysis['total_count'])*0.01,
             f'{count:,}', ha='center', va='bottom', fontsize=9)

plt.tight_layout()
plt.show()

#High exchange rate groups (>=80%)
high_exchange_groups = ['80-85', '85-90', '90-95', '95-100', '100+']
high_exchange_data = group_analysis[
    group_analysis['exchange_rate_group'].isin(high_exchange_groups)
]

print("High Exchange Rate Group Analysis (≥80%):")
print(high_exchange_data)
print(f"\nTotal members in high exchange rate groups: {high_exchange_data['total_count'].sum():,}")
print(f"Members with lifecycle≤1 year in high exchange rate groups: {high_exchange_data['short_lifecycle_count'].sum():,}")
print(f"Percentage with lifecycle≤1 year in high exchange rate groups: {high_exchange_data['short_lifecycle_count'].sum() / high_exchange_data['total_count'].sum() * 100:.2f}%")

#summary_df for Lifecycle Calculation
summary_df = final[final['Cancellation Year'].notna()].groupby('Cancellation Year').agg(
    Total_Cancelled=('Loyalty Number', 'count'),
    Cancelled_Within_1_Year=('lifecycle_months', lambda x: (x <= 12).sum())
).reset_index()

print(summary_df)

#Visualize
plt.figure(figsize=(6,3))

bars1 = plt.bar(summary_df['Cancellation Year'], summary_df['Total_Cancelled'],
                label='Total Cancelled', alpha=0.7, color='mistyrose')

bars2 = plt.bar(summary_df['Cancellation Year'], summary_df['Cancelled_Within_1_Year'],
                label='Cancelled ≤ 1 Year', alpha=0.7, color='rosybrown')

for bar_total, bar_sub, (_, row) in zip(bars1, bars2, summary_df.iterrows()):
    total = row['Total_Cancelled']
    sub = row['Cancelled_Within_1_Year']
    pct = (sub / total * 100) if total > 0 else 0

    plt.text(
        bar_sub.get_x() + bar_sub.get_width()/2,
        bar_sub.get_height()/2,
        f"{pct:.1f}%",
        ha='center', va='center', color='black', fontsize=10, fontweight='bold'
    )

plt.title('Membership Cancellations by Year')
plt.xlabel('Year')
plt.ylabel('Number of Members')
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,3))
plt.hist(cancelled_people["lifecycle_months"], bins=10, edgecolor="black", color='rosybrown')
plt.xlabel("Membership Duration (Months)")
plt.title("Distribution of Membership Duration (Cancelled Members)")
plt.xlabel("Months Enrolled")
plt.ylabel("Number of Members")
plt.show()

"""# RF Score

"""

conditions = [
    final['Total_Flights_Booked'] == 0,
    final['Total_Flights_Booked'] <= 24.9,
    final['Total_Flights_Booked'] <= 49.8,
    final['Total_Flights_Booked'] <= 74.7,
    final['Total_Flights_Booked'] <= 99.6,
    final['Total_Flights_Booked'] <= 124.5,
    final['Total_Flights_Booked'] <= 149,
    final['Total_Flights_Booked'] <= 174,
    final['Total_Flights_Booked'] <= 199.2,
    final['Total_Flights_Booked'] <= 224.1
]

choices = [0,1, 2, 3, 4, 5, 6, 7, 8, 9]

final['f.score'] = np.select(conditions, choices, default=10)

display(final[['Loyalty Number', 'Total_Flights_Booked', 'f.score']].head())

conditions = (flight_df['year_month'] == '201812') & (flight_df['Flights Booked'] != 0)

flight_df['last_book'] = np.where(conditions, flight_df['year_month'], np.nan)

display(flight_df.dropna(subset=['last_book']).head(100))

bookings_only = flight_df[flight_df['Flights Booked'] > 0].copy()


last_booking_date = bookings_only.groupby('Loyalty Number')['year_month'].max().reset_index()
last_booking_date.rename(columns={'year_month': 'last_booking_yyyymm'}, inplace=True)

final = final.drop(columns=['last_booking_yyyymm_x', 'last_booking_yyyymm_y'], errors='ignore')
final = pd.merge(final, last_booking_date, on='Loyalty Number', how='left')

final['last_booking_yyyymm_numeric'] = pd.to_numeric(final['last_booking_yyyymm'], errors='coerce')

display(final.head())

conditions = [
    (final['last_booking_yyyymm_numeric'] >= 201810) & (final['last_booking_yyyymm_numeric'] <= 201812),
    (final['last_booking_yyyymm_numeric'] >= 201807) & (final['last_booking_yyyymm_numeric'] <= 201809),
    (final['last_booking_yyyymm_numeric'] >= 201804) & (final['last_booking_yyyymm_numeric'] <= 201806),
    (final['last_booking_yyyymm_numeric'] >= 201801) & (final['last_booking_yyyymm_numeric'] <= 201803),
    (final['last_booking_yyyymm_numeric'] >= 201710) & (final['last_booking_yyyymm_numeric'] <= 201712),
    (final['last_booking_yyyymm_numeric'] >= 201707) & (final['last_booking_yyyymm_numeric'] <= 201709),
    (final['last_booking_yyyymm_numeric'] >= 201704) & (final['last_booking_yyyymm_numeric'] <= 201706),
    (final['last_booking_yyyymm_numeric'] >= 201701) & (final['last_booking_yyyymm_numeric'] <= 201703)
]


choices = [8, 7, 6, 5, 4, 3, 2,1]

final['r.score'] = np.select(conditions, choices, default=0)

display(final[['Loyalty Number', 'last_booking_yyyymm', 'last_booking_yyyymm_numeric', 'r.score']].head())

final

from google.colab import drive
drive.mount('/content/drive')
final.to_excel("/content/drive/MyDrive/merged_result.xlsx", index=False)

"""# KMeans"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/DA/fr.churn.csv")

df

#Keep data where R and F score are positive
df1 = df[(df['f.score'] > 0) & (df['r.score'] > 0)]
df1

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df1[['f.score', 'r.score']])

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

inertia = []
K = range(1, 10)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(df_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(K, inertia, marker='o')
plt.xlabel('K')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
df1['cluster'] = kmeans.fit_predict(df_scaled)

df1.groupby('cluster')[['f.score', 'r.score','Churn']].mean()

"""# **Clusters**
*   0 : F medium-high, R high -> medium frequency X recent consumption
*   1 : F extremely low, R extremely low -> extremely low frequency X long time without consumption
*   2 : F high, R highest -> highest frequency X recent consumption (most active)
*   3 : F relatively low, R relatively high -> low frequency
"""

df1.groupby('cluster').size()

# Merge final dataframe with clusters
merged_cluster_data = pd.merge(final, df1[['Loyalty Number', 'cluster']], on='Loyalty Number', how='inner')

# Filter out Point Usage Percentage > 100 AND Avg_Distance_Per_Flight > 500
merged_cluster_data_filtered = merged_cluster_data[
    (merged_cluster_data['Point Usage Percentage'] <= 100) &
    (merged_cluster_data['Avg_Distance_Per_Flight'] <= 500)
].copy()

# Filter for cluster 0
merged_cluster_data_filtered_0 = merged_cluster_data_filtered[merged_cluster_data_filtered['cluster'] == 0]

# Calculate centroids
centroids_new_features = merged_cluster_data_filtered_0.groupby('cluster')[['Total_Points_Accumulated', 'Point Usage Percentage']].mean().reset_index()

plt.figure(figsize=(8, 5))

# Plot the entire dataset in the background (zorder=0)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data[
        (merged_cluster_data['Point Usage Percentage'] <= 100) &
        (merged_cluster_data['Avg_Distance_Per_Flight'] <= 500)
    ],
    color='gainsboro',
    s=50,
    alpha=0.5,
    label='Others',
    zorder=0
)

# Plot non-churned members (zorder=1)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_0,
    color='rosybrown',
    s=50,
    alpha=0.9,
    label='Cluster 0',
    zorder=1
)

# Plot centroids (zorder=3)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=centroids_new_features,
    marker='X',
    s=200,
    color='black',
    label='Centroid',
    zorder=3
)

# Annotate centroids with cluster number
for i, row in centroids_new_features.iterrows():
    plt.text(row['Point Usage Percentage'], row['Total_Points_Accumulated'], f' {int(row['cluster'])}',
             horizontalalignment='left', verticalalignment='bottom', fontsize=12, color='black', weight='bold', zorder=4)

plt.title('K-Means Cluster 0 (Point Usage Percentage vs Total Points Accumulated)')
plt.xlabel('Point Usage Percentage')
plt.ylabel('Total Points Accumulated')
plt.legend()
plt.ylim(0, 7000)
plt.show()

# Filter for cluster 1
merged_cluster_data_filtered_1 = merged_cluster_data_filtered[merged_cluster_data_filtered['cluster'] == 1]

# Calculate centroids for the new features on the filtered data
centroids_new_features = merged_cluster_data_filtered_1.groupby('cluster')[['Total_Points_Accumulated', 'Point Usage Percentage']].mean().reset_index()

plt.figure(figsize=(8, 5))

# Plot non-churned members (zorder=1)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_1[merged_cluster_data_filtered_1['Churn'] == 0],
    color='plum',
    s=50,
    alpha=0.7,
    label='Non-Churned',
    zorder=1
)

# Plot churned members (zorder=2)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_1[merged_cluster_data_filtered_1['Churn'] == 1],
    color='red',
    s=50,
    alpha=0.7,
    label='Churned',
    zorder=2
)

# Plot centroids (zorder=3)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=centroids_new_features,
    marker='X',
    s=200,
    color='black',
    label='Centroid',
    zorder=3
)

# Annotate centroids with their cluster number
for i, row in centroids_new_features.iterrows():
    plt.text(row['Point Usage Percentage'], row['Total_Points_Accumulated'], f' {int(row['cluster'])}',
             horizontalalignment='left', verticalalignment='bottom', fontsize=12, color='black', weight='bold', zorder=4)

plt.title('K-Means Cluster 1 (Point Usage Percentage vs Total Points Accumulated)')
plt.xlabel('Point Usage Percentage')
plt.ylabel('Total Points Accumulated')
plt.legend(title='Churn Status')
plt.ylim(0, 7000) # Set y-axis limit
plt.show()

# Filter for cluster 2
merged_cluster_data_filtered_2 = merged_cluster_data_filtered[merged_cluster_data_filtered['cluster'] == 2]

# Calculate centroids
centroids_new_features = merged_cluster_data_filtered_2.groupby('cluster')[['Total_Points_Accumulated', 'Point Usage Percentage']].mean().reset_index()

plt.figure(figsize=(8, 5))

# Plot non-churned members (zorder=1)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_2[merged_cluster_data_filtered_2['Churn'] == 0],
    color='thistle',
    s=50,
    alpha=0.7,
    label='Non-Churned',
    zorder=1
)

# Plot churned members (zorder=2)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_2[merged_cluster_data_filtered_2['Churn'] == 1],
    color='red',
    s=50,
    alpha=0.7,
    label='Churned',
    zorder=2
)

# Plot centroids (zorder=3)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=centroids_new_features,
    marker='X',
    s=200,
    color='black',
    label='Centroid',
    zorder=3
)

# Annotate centroids with cluster number
for i, row in centroids_new_features.iterrows():
    plt.text(row['Point Usage Percentage'], row['Total_Points_Accumulated'], f' {int(row['cluster'])}',
             horizontalalignment='left', verticalalignment='bottom', fontsize=12, color='black', weight='bold', zorder=4)

plt.title('K-Means Cluster 2 (Point Usage Percentage vs Total Points Accumulated)')
plt.xlabel('Point Usage Percentage')
plt.ylabel('Total Points Accumulated')
plt.legend(title='Churn Status')
plt.ylim(0, 7000)
plt.show()

# Filter for cluster 3
merged_cluster_data_filtered_3 = merged_cluster_data_filtered[merged_cluster_data_filtered['cluster'] == 3]

# Calculate centroids for the new features on the filtered data
centroids_new_features = merged_cluster_data_filtered_3.groupby('cluster')[['Total_Points_Accumulated', 'Point Usage Percentage']].mean().reset_index()

plt.figure(figsize=(10, 6))

# Plot non-churned members (zorder=1)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_3[merged_cluster_data_filtered_3['Churn'] == 0],
    color='pink',
    s=50,
    alpha=0.7,
    label='Non-Churned',
    zorder=1
)

# Plot churned members (zorder=2)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=merged_cluster_data_filtered_3[merged_cluster_data_filtered_3['Churn'] == 1],
    color='red',
    s=50,
    alpha=0.7,
    label='Churned',
    zorder=2
)

# Plot centroids (zorder=3)
sns.scatterplot(
    x='Point Usage Percentage',
    y='Total_Points_Accumulated',
    data=centroids_new_features,
    marker='X',
    s=200,
    color='black',
    label='Centroid',
    zorder=3
)

# Annotate centroids with their cluster number
for i, row in centroids_new_features.iterrows():
    plt.text(row['Point Usage Percentage'], row['Total_Points_Accumulated'], f' {int(row['cluster'])}',
             horizontalalignment='left', verticalalignment='bottom', fontsize=12, color='black', weight='bold', zorder=4)

plt.title('K-Means Cluster 3 (Point Usage Percentage vs Total Points Accumulated)')
plt.xlabel('Point Usage Percentage')
plt.ylabel('Total Points Accumulated')
plt.legend(title='Churn Status')
plt.ylim(0, 7000) # Set y-axis limit
plt.show()

#Average distance distribution between clusters
avg_distance_by_cluster = merged_cluster_data.groupby('cluster')['Avg_Distance_Per_Flight'].mean().reset_index()
display(avg_distance_by_cluster)

#Gender distribution among clusters
gender_counts_by_cluster = merged_cluster_data.groupby('cluster')['Gender'].value_counts().unstack(fill_value=0)
display(gender_counts_by_cluster)

#Loyalty card distribution among clusters
lc_counts_by_cluster = merged_cluster_data.groupby('cluster')['Loyalty Card'].value_counts().unstack(fill_value=0)
display(lc_counts_by_cluster)

#Education distribution among clusters
education_counts_by_cluster = merged_cluster_data.groupby('cluster')['Education'].value_counts().unstack(fill_value=0)
display(education_counts_by_cluster)

"""#Seasonal Bookings"""

flight_data_with_clusters = pd.merge(flight_df, df1[['Loyalty Number', 'cluster']], on='Loyalty Number', how='inner')
flight_data_with_clusters.head()

filtered_flight_data = flight_data_with_clusters[
    (flight_data_with_clusters['year_month'] >= '201701') &
    (flight_data_with_clusters['year_month'] <= '201812')
].copy()
filtered_flight_data.head()

monthly_bookings_by_cluster = filtered_flight_data.groupby(['year_month', 'cluster'])['Total Flights'].sum().reset_index()
monthly_bookings_by_cluster.head()

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates

# 1. Convert 'year_month' to datetime object
monthly_bookings_by_cluster['year_month'] = pd.to_datetime(monthly_bookings_by_cluster['year_month'], format='%Y%m')

#color palette
cluster_colors = {
    0: 'rosybrown',
    1: 'indianred',
    2: 'pink',
    3: 'palevioletred'
}

plt.figure(figsize=(10, 6))
sns.lineplot(
    x='year_month',
    y='Total Flights',
    hue='cluster',
    data=monthly_bookings_by_cluster,
    marker='o',
    palette=cluster_colors
)
plt.title('Monthly Flights Booked by Cluster (2017-2018)')
plt.xlabel('Month')
plt.ylabel('Total Flights')

# Set labels
ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m')) # Format as YYYY-MM


plt.xticks(rotation=45, ha='right')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.margins(x=0.04)
plt.show()

"""# Redeem Rate Analysis"""

#Churn by Redeem Rate
bins = np.linspace(0, 100, 21)
labels = [f'{int(bins[i])}-{int(bins[i+1])}' for i in range(len(bins)-1)]

final['redeem_bin'] = pd.cut(final['Point Usage Percentage'], bins=bins, labels=labels, include_lowest=True)

new_categories = list(final['redeem_bin'].cat.categories) + ['> 100']
final['redeem_bin'] = final['redeem_bin'].cat.set_categories(new_categories)

final.loc[final['Point Usage Percentage'] > 100, 'redeem_bin'] = '> 100'

churn_by_redeem_bin = (
      final.groupby('redeem_bin')['Cancellation Year']
      .apply(lambda x: x.notna().mean())
      .reset_index(name='churn_rate')
)

bin_counts = (
    final.groupby('redeem_bin')
         .size()
         .reset_index(name='Loyalty Number')
)
print(churn_by_redeem_bin)

churn_by_redeem_bin['churn_rate'] *= 100

# Merge churn rate with total counts
plot_df = churn_by_redeem_bin.merge(bin_counts, on='redeem_bin')
plot_df = plot_df.sort_values(by='redeem_bin')

#Average Flight Distance by Redeem Rate
distance_summary = (final.groupby('redeem_bin')['Total_Distance']
         .agg(['sum', 'count'])
         .reset_index()
         .rename(columns={'sum': 'Total_Distance', 'count': 'Member_Count'})
)

# Average Distance
distance_summary['Avg_Distance'] = (
    distance_summary['Total_Distance'] / distance_summary['Member_Count']
)

distance_summary = distance_summary.sort_values(by='redeem_bin')

#Visualize
plt.figure(figsize=(8, 5))
plt.barh(distance_summary['redeem_bin'], distance_summary['Avg_Distance'],
         color='rosybrown', edgecolor='black')

plt.title("Average Total Distance by Redeem Bin", fontsize=14)
plt.xlabel("Average Total Distance per Member", fontsize=12)
plt.ylabel("Redeem Rate (%)", fontsize=12)

for index, value in enumerate(distance_summary['Avg_Distance']):
    plt.text(value, index, f'{value:,.0f}', va='center', ha='left', fontsize=10)

plt.tight_layout()
plt.show()

#Member Count and Churn Rate by Redeem Rate
fig, ax1 = plt.subplots(figsize=(8,5))

# Bar chart for total people
ax1.bar(plot_df['redeem_bin'].astype(str), plot_df['Loyalty Number'], color='rosybrown') # Changed color to lightcoral
ax1.set_xticklabels(plot_df['redeem_bin'].astype(str), rotation=45, ha='right')
ax1.set_ylabel('Number of People')
ax1.set_xlabel('Point Usage %')

# churn rate (line chart)
ax2 = ax1.twinx()
ax2.plot(plot_df['redeem_bin'].astype(str), plot_df['churn_rate'], marker='o', color='firebrick') # Changed color to firebrick
ax2.set_ylabel('Churn Rate (%)')

plt.title('Churn Rate vs. Points Redeemed Percentage')
plt.tight_layout()
plt.show()

# Filter out members with point usage percentage over 100%
final_usage_filtered = final[final['Point Usage Percentage'] <= 100].copy()

plt.figure(figsize=(8, 5))
sns.scatterplot(data=final_usage_filtered, x='Point Usage Percentage', y='Total_Points_Accumulated', hue='Churn', alpha=0.6,palette=['rosybrown', 'red'])

plt.title('Total Points Accumulated vs. Point Usage Percentage (<= 100%)')
plt.xlabel('Point Usage Percentage')
plt.ylabel('Total Points Accumulated ')
plt.show()

"""# Member Activity"""

#Explore whether members are active within 3 months of cancellation
cancelled_20172018['months_before_cancellation'] = (cancelled_20172018['CancellationYearMonth'] // 100- cancelled_20172018['YearMonth'] // 100) * 12 \
                                         + cancelled_20172018['CancellationYearMonth'] % 100-(cancelled_20172018['YearMonth'] % 100)
# Only keep data within 3 months of cancellation
within_3_months = cancelled_20172018[cancelled_20172018['months_before_cancellation'].between(0, 3)].copy()

# Label which rows have orders
within_3_months['has_order'] = within_3_months['Total Flights'] != 0

active_status = (
    within_3_months.groupby(['Loyalty Number', 'Cancellation Year'])['has_order']
    .any()
    .reset_index()
)
active_status.rename(columns={'has_order': 'is_active'}, inplace=True)

# Active/Inactive members per year
summary_by_year = (
    active_status.groupby('Cancellation Year')['is_active']
    .value_counts()
    .unstack(fill_value=0)
    .rename(columns={True: 'Active', False: 'Inactive'})
)

print(summary_by_year)

#Visualize
ax = summary_by_year.plot(kind='bar', stacked=True, figsize=(6,3))

plt.title('Active vs Inactive Members Within 3 Months Before Cancellation by Year')
plt.xlabel('Cancellation Year')
plt.ylabel('Number of Members')
plt.xticks(rotation=0)
plt.legend(title='Status')

for i, year in enumerate(summary_by_year.index):
    active_count = summary_by_year.loc[year, 'Active']
    inactive_count = summary_by_year.loc[year, 'Inactive']

    # Active
    ax.text(i, active_count / 2, str(active_count), ha='center', va='center', color='black', fontweight='bold')

    # Inactive
    ax.text(i, inactive_count / 2, str(inactive_count), ha='center', va='center', color='black', fontweight='bold')

plt.tight_layout()
plt.show()

!pip install lifelines

from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test

df = final.copy()

df['_orig_end_yyyymm'] = df['end_yyyymm']

# Convert start_yyyymm and end_yyyymm (NaN means not yet cancelled) to YYYYMM string and fill with 201812 as observation end
df['start_yyyymm'] = df['start_yyyymm'].astype(str).str.zfill(6)
df['end_yyyymm_for_calc'] = df['end_yyyymm'].fillna('201812').astype(str).str.zfill(6)

# Convert to datetime
df['start_date'] = pd.to_datetime(df['start_yyyymm'], format='%Y%m')
df['end_date'] = pd.to_datetime(df['end_yyyymm_for_calc'], format='%Y%m')

# Churn: Yes = 1, No = 0
df['churn'] = df['_orig_end_yyyymm'].notna().astype(int)

#Cohort Analysis (calculating average months by redeem bins)
bins = list(range(0, 101, 5)) + [np.inf]
labels = [f"{bins[i]}-{bins[i+1]}%" for i in range(len(bins)-1)]
labels[-2] = "95-100%"
labels[-1] = ">100%"

df['redeem_bin'] = pd.cut(df['Point Usage Percentage'],
                          bins=bins,
                          labels=labels,
                          right=False,
                          include_lowest=True)

df['cohort_year'] = df['start_date'].dt.year.astype(str)

# Calculate average months_enrolled for cohort_year × redeem_bin
cohort_summary = (
    df.groupby(['cohort_year','redeem_bin'])
    .agg(
        avg_months_enrolled=('months_enrolled','mean'),
        member_count=('Loyalty Number','count')
    )
    .reset_index()
)

print(cohort_summary.head())

#Survival Analysis (Kaplan–Meier) — High vs Low redeem groups
duration = df['lifecycle_months']
event = df['churn']

kmf_high = KaplanMeierFitter()
kmf_low = KaplanMeierFitter()
kmf_0_5 = KaplanMeierFitter()

mask_high =(df['Point Usage Percentage'] >= 80)
mask_low = (df['Point Usage Percentage'] >= 5) & (df['Point Usage Percentage'] < 80)
# 0–5% redeem group
mask_0_5 = (df['Point Usage Percentage'] >= 0) & (df['Point Usage Percentage'] < 5)

# Fit
kmf_high.fit(durations=duration[mask_high], event_observed=event[mask_high], label='Redeem >=80%')
kmf_low.fit(durations=duration[mask_low], event_observed=event[mask_low], label='Redeem 5-80%')
kmf_0_5.fit(durations=duration[mask_0_5],event_observed=event[mask_0_5],label='Redeem 0–5%')

# Plot KM curves
plt.figure(figsize=(8,5))
ax = plt.subplot(111)
kmf_high.plot_survival_function(ax=ax, color='rosybrown')
kmf_low.plot_survival_function(ax=ax, color='yellowgreen')
kmf_0_5.plot_survival_function(ax=ax, color='lightcoral')
plt.title('Kaplan–Meier Survival Curve for Redeem Groups')
plt.xlabel('Months since Enrollment')
plt.ylabel('Survival Probability (not churned)')
plt.tight_layout()
plt.show()

# Log-rank test
results = logrank_test(
    duration[mask_high], duration[mask_low],
    event_observed_A=event[mask_high], event_observed_B=event[mask_low]
)
print("Log-rank test p-value:", results.p_value)
print(results.summary)